### PR TITLE
Short trick to count digits in a number

### PR DESCRIPTION
**Pull request by kalvik09**

### CODE REVIEW

**Comment by sohamm20** [comment]
You are missing an edge case, N = 0. Correct it

**Review by Atharv-Nalwade — CHANGES_REQUESTED** [review]
Do handle cases when numbers are negative 
and for the number 0 your code is breaking

**Comment by kalvik09** [comment]
Can you please check again?
Thanks

**Review by Atharv-Nalwade — APPROVED** [review]
Good Work

**Pull request merged**
